#! /bin/sh

#sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

xrandr --output DP-4 --mode 1920x1080 --rate 144.00

bspc config border_width         1
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -add copyq state=floating

setxkbmap -option grp:alt_shift_toggle us,dk &
#### CUSTOM CONFIG ####
feh --bg-fill $HOME/Downloads/wal3.png &
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "#ee00ff"
bspc config active_border_color "#38369C"
bspc config focused_border_color "#00FFFF"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer false
bspc config bottom_padding 5
bspc config top_padding 30
bspc config left_padding 5
bspc config right_padding 5

#Intelli J
#bspc set wmname LG3D
wmname LG3D &
imwheel &
#source ~/.zshrc
~/.config/wpg/./wp_init.sh &
~/.config/polybar/launch.sh --forest
~/.config/scripts/dunst.sh
~/.config/scripts/bspswallow/bspswallow.sh

#picom --experimental-backends &
xsetroot -cursor_name left_ptr

## Process spawning rules
function runs {
  # Helper that returns false if a process is running
  if pgrep ${1}; then return 1; fi
  return 0
}

runs copyq && `copyq &`
